(function(){
'use strict';
var WA='https://wa.me/201019053288?text=';
var PL={'index.html':'الصفحة الرئيسية','':'','services.html':'صفحة الخدمات','about.html':'صفحة من نحن','contact.html':'صفحة التواصل','portfolio.html':'معرض الأعمال','project-detail.html':'تفاصيل المشروع','packages.html':'باقات وأسعار'};
var BM=[{k:'VR',m:'أريد احجز جولة VR لمشروعي'},{k:'جولة',m:'أريد احجز جولة VR لمشروعي'},{k:'معاينة',m:'أريد احجز معاينة مجانية'},{k:'معماري',m:'أريد الاستفسار عن التصميم المعماري'},{k:'تجاري',m:'أريد بدء مشروعي التجاري'},{k:'تشطيب',m:'أريد الاستفسار عن خدمة التشطيب'},{k:'تصميم',m:'أريد الاستفسار عن خدمة التصميم الداخلي'},{k:'استشارة',m:'أريد احجز استشارة مجانية مع Creative3Design'},{k:'مشروع',m:'أريد بدء مشروعي مع Creative3Design'},{k:'رحل',m:'أريد البدء برحلة تصميم مشروعي'},{k:'أعمال',m:'أعجبتني أعمالكم وأريد الاستفسار'},{k:'تواصل',m:'أريد التواصل مع فريق Creative3Design'}];
var PD={'contact.html':'مرحباً،\nزرت صفحة التواصل وأريد التحدث مع فريق Creative3Design.','portfolio.html':'مرحباً،\nأعجبتني أعمالكم وأريد الاستفسار عن مشروع مماثل.','project-detail.html':'مرحباً،\nرأيت مشروعكم وأريد احجز استشارة مجانية لمشروع مماثل.','about.html':'مرحباً،\nتعرفت على فريق Creative3Design وأريد الاستفسار عن خدماتكم.'};
function getPage(){var p=(window.location.pathname.split('/').pop()||'').replace(/[?#].*/,'');if(p&&p.indexOf('.')===-1)p=p+'.html';return p||'index.html';}
function build(t,pg){var lbl=PL[pg]||'الموقع';var act='';for(var i=0;i<BM.length;i++){if(t.indexOf(BM[i].k)!==-1){act=BM[i].m;break;}}if(!act){if(PD[pg])return PD[pg];act='أريد الاستفسار عن خدمات Creative3Design';}return 'مرحباً،\n'+act+'\n\nمن: '+lbl;}
function run(){var pg=getPage();var ls=document.querySelectorAll('a[href*="wa.me/201019053288"]');for(var i=0;i<ls.length;i++){var a=ls[i];if(a.id==='fin-wa-btn'||a.id==='des-wa-btn'||a.id==='arch-wa-btn')continue;var t=((a.getAttribute('data-ar')||'')+' '+(a.textContent||'')).trim();if(/^[\d\s]+$/.test(t))continue;a.href=WA+encodeURIComponent(build(t,pg));}}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',run);}else{run();}
})();